version: '2.4'

services:
  webapp:
    container_name: webapp
    build:
      context: ./webapp
    image: webapp
    ports:
      - 80:80
    command: sh -c "uvicorn main:app --log-config log.ini --host 0.0.0.0 --port 80"

  performance_tests:
    depends_on:
      - webapp
    container_name: performance_tests
    build:
      context: ./performance_tests
    image: performance_tests
    environment:
      TEST_APP_URL: http://webapp:80
    command: python tests.py
